disabled_rules:
- trailing_whitespace
- identifier_name
- todo
- multiple_closures_with_trailing_closure
- line_length
- function_parameter_count
- cyclomatic_complexity
- weak_delegate
- class_delegate_protocol
- force_cast

file_length:
- 1100

function_body_length:
- 150 # Warning
- 200 # Error

type_body_length:
- 400 # Warning
- 500 # Error

excluded:
- Pods
